name: DevOps CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify project files
        run: ls

      - name: Build step
        run: echo "Building static web app..."

      - name: Test step
        run: echo "No tests configured"

      - name: CI Completed
        run: echo "CI pipeline executed successfully!"

      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"CI Pipeline executed successfully ðŸš€"}' \
          ${{ secrets.SLACK_WEBHOOK }}

